import React, { useEffect, useState } from "react";
import "../styles/Dates.css"; // optional if you want custom styling
import axios from "axios";

const Dates = () => {
  const [dateIdeas, setDateIdeas] = useState([]);
  const [activeDate, setActiveDate] = useState(null);
  const [loading, setLoading] = useState(true);

  const currentUserEmail =
    localStorage.getItem("rememberedUser") ||
    sessionStorage.getItem("loggedInUser");

  useEffect(() => {
    const fetchDates = async () => {
      try {
        const res = await axios.get(
          `http://localhost:5000/api/shared-dates/for/${currentUserEmail}`
        );
        if (res.data.success) {
          setDateIdeas(res.data.dates);
        } else {
          console.error("❌ Failed to load shared dates:", res.data.message);
        }
      } catch (err) {
        console.error("❌ Error fetching shared dates:", err);
      } finally {
        setLoading(false);
      }
    };

    fetchDates();
  }, [currentUserEmail]);

  return (
    <div className="dates-page">
      <h1>📅 Shared Date Plans</h1>
      {loading ? (
        <p>Loading...</p>
      ) : dateIdeas.length === 0 ? (
        <p>No shared dates yet.</p>
      ) : (
        <ul className="date-list">
          {dateIdeas.map((date, index) => (
            <li key={index} className="date-item">
            <div className="date-label">
              <strong>Generated by:</strong>
              <span>{date.senderEmail === currentUserEmail ? "You" : date.senderName || date.senderEmail}</span>
            </div>
          
            <button
              onClick={() => setActiveDate(date.message)}
              className="view-date-button"
            >
              View Plan
            </button>
          </li>
          
          ))}
        </ul>
      )}

      {activeDate && (
        <div className="date-modal-overlay">
          <div className="date-modal">
            <h3>💖 Custom Date Plan</h3>
            <p style={{ whiteSpace: "pre-wrap" }}>{activeDate}</p>
            <button onClick={() => setActiveDate(null)} className="close-modal-button">
              Close
            </button>
          </div>
        </div>
      )}
    </div>
  );
};

export default Dates;
